addons:
  mariadb: '10.0'
before_install:
  - mysql -e 'CREATE DATABASE example;'
language: node_js
node_js:
 - "8"
install:
  - npm i
  - npm run init
  - npm i -g nyc
  - npm i --save-dev coveralls
script:
  - NODE_ENV=test nyc --reporter=lcovonly ./node_modules/mocha/bin/_mocha && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
